title: My Academic Page
url: "https://e3computing.org"    # your domain
baseurl: "/~test"            # "" if root domain

author:
  name: Marcus J. Reinhardt
  homepage: "https://example.com/about"

year_from: 2018

# Exclude from processing.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - Makefile

